name: DoomboheadPlugin
version: '${project.version}'
main: me.alientation.doomboheadplugin.DoomboheadPlugin
api-version: 1.19
authors: [ Alientation ]
description: Plugin for the Doombohead Server

permissions:
  alphabet:
    description: Allows alphabet command
    default: true
  alphabet.list:
    description: Allows alphabet list command
    default: true
  alphabet.add:
    description: Allows alphabet edit command
    default: op
  customGUI:
    description: Allows custom gui command
    default: true
  admin:
    description: become admin
    default: true